// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

import db from "./src/config/database.js";

const host = `postgresql://${db.user}:${db.password}@${db.host}:${db.port}/${db.database}`;

export default defineConfig({
  schema: "src/prisma/schema.prisma",
  migrations: {
    path: "src/prisma/migrations",
    seed: "src/prisma/seed.js",
  },
  datasource: {
    url: host,
  },
});
